export enum SOCIAL {
  FACEBOOK = 'facebook',
  TWITTER = 'twitter',
  INSTAGRAM = 'instagram',
  LINKEDIN = 'linkedin',
  PINTEREST = 'pinterest',
  YOUTUBE = 'youtube',
  SNAPCHAT = 'snapchat',
  WHATSAPP = 'whatsapp',
  TELEGRAM = 'telegram',
  VIBER = 'viber',
  SKYPE = 'skype',
  WECHAT = 'wechat',
  WEIBO = 'weibo',
  TUMBLR = 'tumblr',
}
