apiVersion: apps/v1
kind: Deployment
metadata:
  name: bezo-deployment
  namespace: bezo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: bezo
          image: bezo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7200
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bezo-secret
                  key: DATABASE_URL

            - name: MAIL_TRANSPORT
              valueFrom:
                secretKeyRef:
                  name: bezo-secret
                  key: MAIL_TRANSPORT

            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: bezo-settings
                  key: MAIL_FROM

            - name: environment
              valueFrom:
                configMapKeyRef:
                  name: bezo-settings
                  key: ENVIRONMENT

            - name: SMS_API
              valueFrom:
                configMapKeyRef:
                  name: bezo-settings
                  key: SMS_API

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bezo-secret
                  key: JWT_SECRET

            - name: AZURE_STORAGE_CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: bezo-settings
                  key: AZURE_STORAGE_CONTAINER

            - name: AZURE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: bezo-secret
                  key: AZURE_CONNECTION_STRING
